#!/bin/sh
cd Downloads && mkdir nvidia && cd nvidia
wget -c http://http.kali.org/kali/pool/contrib/g/glx-alternatives/glx-alternative-nvidia_1.2.2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libcuda1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-alternative_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-driver_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-kernel-dkms_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-legacy-check_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-open-gpu-kernel-modules/nvidia-open-kernel-dkms_525.125.06-1_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-persistenced/nvidia-persistenced_525.85.05-1_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-settings/nvidia-settings_525.125.06-1_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers-tesla/nvidia-tesla-alternative_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers-tesla/nvidia-tesla-legacy-check_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-vdpau-driver_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/xserver-xorg-video-nvidia_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/f/firmware-nonfree/firmware-misc-nonfree_20230515-3%2bkali1_all.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers-tesla/firmware-nvidia-tesla-gsp_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/main/f/flashrom/flashrom_1.3.0-2.1_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/g/gpustat/gpustat_1.0.0-1_all.deb
wget -c http://http.kali.org/kali/pool/contrib/h/hashcat-meta/hashcat-nvidia_20210201_all.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libegl-nvidia0_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libgl1-nvidia-glvnd-glx_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libgles-nvidia1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libgles-nvidia2_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libglx-nvidia0_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvcuvid1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-allocator1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-cfg1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-compiler_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-egl-gbm/libnvidia-egl-gbm1_1.1.0-3_amd64.deb
wget -c http://http.kali.org/kali/pool/main/e/egl-wayland/libnvidia-egl-wayland1_1.1.12-1_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-eglcore_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-encode1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-glcore_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-glvkspirv_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-ml1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-nvvm4_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-ptxjitcompiler1_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-rtcore_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-cuda-toolkit/libnvvm4_12.0.140%7e12.0.1-2_amd64.deb
wget -c http://http.kali.org/kali/pool/main/libv/libvdpau/libvdpau1_1.5-2_amd64.deb
wget -c http://http.kali.org/kali/pool/main/libx/libxnvctrl/libxnvctrl0_525.125.06-1_amd64.deb
wget -c http://http.kali.org/kali/pool/main/n/numba/numba-doc_0.56.4%2bdfsg-2_all.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-detect_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-driver-bin_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-driver-libs_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-egl-common_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-egl-icd_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-support/nvidia-installer-cleanup_20220217%2b3_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-support/nvidia-kernel-common_20220217%2b3_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-kernel-support_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-modprobe/nvidia-modprobe_535.54.03-1_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-open-gpu-kernel-modules/nvidia-open-kernel-source_525.125.06-1_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-open-gpu-kernel-modules/nvidia-open-kernel-support_525.125.06-1_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-opencl-common_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-opencl-icd_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers-tesla/nvidia-powerd_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-smi_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/n/nvidia-support/nvidia-support_20220217%2b3_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-vulkan-common_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-vulkan-icd_525.125.06-2_amd64.deb
wget -c http://http.kali.org/kali/pool/main/p/psensor/psensor_1.1.5-1.4_amd64.deb
wget -c http://http.kali.org/kali/pool/main/n/numba/python3-numba_0.56.4%2bdfsg-2_amd64.deb
wget -c http://http.kali.org/kali/pool/contrib/p/python-pynvml/python3-pynvml_12.535.77-1_amd64.deb
wget -c http://http.kali.org/kali/pool/main/t/truecrack/truecrack_3.6%2bgit20150326-0kali3_amd64.deb
wget -c http://http.kali.org/kali/pool/main/libv/libvdpau/vdpau-driver-all_1.5-2_amd64.deb
wget -c http://http.kali.org/kali/pool/main/x/xserver-xorg-video-nouveau/xserver-xorg-video-nouveau_1.0.17-2_amd64.deb
dpkg -i *.deb
apt --fix-broken install
dpkg -i *.deb
apt install aptitude -y && aptitude install locales -y && locale-gen en_US.UTF-8 && localedef -i en_US -f UTF-8 en_US.UTF-8 && export LANGUAGE=en_US.UTF-8 && export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && locale-gen en_US.UTF-8 && apt-get update -y && apt-get full-upgrade -y && aptitude install wget -y && apt-get install python3 python3-venv python3-pip -y && apt-get autoclean && apt-get clean cache && apt update -y && apt-get full-upgrade -y

