#!/bin/sh
cd Downloads && mkdir nvidia && cd nvidia
#!/bin/sh
wget -c https://kali.download/kali/pool/contrib/g/glx-alternatives/glx-alternative-nvidia_1.2.2_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libcuda1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-alternative_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-driver_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-kernel-dkms_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-legacy-check_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-open-gpu-kernel-modules/nvidia-open-kernel-dkms_525.147.05-3_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-persistenced/nvidia-persistenced_525.147.05-1_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-settings/nvidia-settings_525.147.05-1_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers-tesla/nvidia-tesla-alternative_525.147.05-7_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers-tesla/nvidia-tesla-legacy-check_525.147.05-7_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-vdpau-driver_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/xserver-xorg-video-nvidia_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free-firmware/f/firmware-nonfree/firmware-misc-nonfree_20230625-2%2bkali1_all.deb
wget -c https://kali.download/kali/pool/non-free-firmware/n/nvidia-graphics-drivers-tesla/firmware-nvidia-tesla-gsp_525.147.05-7_amd64.deb
wget -c https://kali.download/kali/pool/main/f/flashrom/flashrom_1.3.0-2.1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/contrib/g/gpustat/gpustat_1.1.1-1_all.deb
wget -c https://kali.download/kali/pool/contrib/h/hashcat-meta/hashcat-nvidia_20210201_all.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libegl-nvidia0_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libgl1-nvidia-glvnd-glx_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libgles-nvidia1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libgles-nvidia2_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libglx-nvidia0_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvcuvid1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-allocator1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-cfg1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-compiler_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-egl-gbm/libnvidia-egl-gbm1_1.1.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/e/egl-wayland/libnvidia-egl-wayland1_1.1.13-1_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-eglcore_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-encode1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-glcore_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-glvkspirv_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-ml1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-nvvm4_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-ptxjitcompiler1_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/libnvidia-rtcore_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-cuda-toolkit/libnvvm4_12.0.140%7e12.0.1-4_amd64.deb
wget -c https://kali.download/kali/pool/main/libv/libvdpau/libvdpau1_1.5-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libx/libxnvctrl/libxnvctrl0_535.171.04-1_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-detect_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-driver-bin_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-driver-libs_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-egl-common_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-egl-icd_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-support/nvidia-installer-cleanup_20240109%2b1_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-support/nvidia-kernel-common_20240109%2b1_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-kernel-support_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-modprobe/nvidia-modprobe_535.161.07-1_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-open-gpu-kernel-modules/nvidia-open-kernel-source_525.147.05-3_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-open-gpu-kernel-modules/nvidia-open-kernel-support_525.147.05-3_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-opencl-common_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-opencl-icd_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-powerd_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-smi_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/contrib/n/nvidia-support/nvidia-support_20240109%2b1_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-suspend-common_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-vulkan-common_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/non-free/n/nvidia-graphics-drivers/nvidia-vulkan-icd_525.147.05-10_amd64.deb
wget -c https://kali.download/kali/pool/main/p/psensor/psensor_1.1.5-1.4_amd64.deb
wget -c https://kali.download/kali/pool/contrib/p/python-pynvml/python3-pynvml_12.535.133-1_amd64.deb
wget -c https://kali.download/kali/pool/main/t/truecrack/truecrack_3.6%2bgit20150326-0kali3_amd64.deb
wget -c https://kali.download/kali/pool/main/libv/libvdpau/vdpau-driver-all_1.5-2_amd64.deb
wget -c https://kali.download/kali/pool/main/x/xserver-xorg-video-nouveau/xserver-xorg-video-nouveau_1.0.17-3_amd64.deb
dpkg -i *.deb
apt --fix-broken install -y
dpkg -i *.deb
apt install aptitude -y && aptitude install locales -y && locale-gen en_US.UTF-8 && localedef -i en_US -f UTF-8 en_US.UTF-8 && export LANGUAGE=en_US.UTF-8 && export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && locale-gen en_US.UTF-8 && apt-get update -y && apt-get full-upgrade -y && aptitude install wget -y && apt-get install python3 python3-venv python3-pip -y && apt-get autoclean && apt-get clean cache && apt update -y && apt-get full-upgrade -y
reboot
