#!/bin/sh
cd Downloads && mkdir gnome && cd gnome
wget -c https://kali.download/kali/pool/main/libc/libcbor/libcbor0.10_0.10.2-1.1_amd64.deb
wget -c https://kali.download/kali/pool/main/f/fwupd/libfwupd2_1.9.6-1_amd64.deb
wget -c https://kali.download/kali/pool/main/f/fwupd/fwupd_1.9.6-1_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-desktop-core_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-desktop-gnome_2023.4.3_all.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-desktop-kde_2023.4.3_all.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-desktop-xfce_2023.4.3_all.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-system-core_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-linux-core_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-system-cli_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-system-gui_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-linux-headless_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-top10_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-linux-default_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-linux-firmware_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-linux-labs_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-linux-wsl_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-802-11_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-bluetooth_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-crypto-stego_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-database_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-detect_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-exploitation_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-forensics_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-fuzzing_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-gpu_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-hardware_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-identify_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-information-gathering_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-passwords_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-post-exploitation_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-protect_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-recover_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-reporting_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-respond_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-reverse-engineering_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-rfid_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-sdr_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-sniffing-spoofing_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-social-engineering_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-voip_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-vulnerability_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-web_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-windows-resources_2023.4.3_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-tools-wireless_2023.4.3_amd64.deb
#!/bin/sh
wget -c https://kali.download/kali/pool/main/a/adwaita-icon-theme/adwaita-icon-theme_45.0-2_all.deb
wget -c https://kali.download/kali/pool/main/a/aisleriot/aisleriot_3.22.23-1_amd64.deb
wget -c https://kali.download/kali/pool/main/a/alacarte/alacarte_3.50.0-2_all.deb
wget -c https://kali.download/kali/pool/main/a/at-spi2-core/at-spi2-common_2.50.0-1_all.deb
wget -c https://kali.download/kali/pool/main/a/at-spi2-core/at-spi2-core_2.50.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/b/baobab/baobab_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/b/blueman/blueman_2.3.5-3_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-browser-connector/gnome-browser-connector_42.1-4_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-browser-connector/chrome-gnome-shell_42.1-4_all.deb
wget -c https://kali.download/kali/pool/main/c/compiz/compiz-gnome_0.8.18-5_amd64.deb
wget -c https://kali.download/kali/pool/main/d/desktop-base/desktop-base_12.0.6%2bnmu1%2bkali1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-session/gnome-session-common_45.0-2_all.deb
wget -c https://kali.download/kali/pool/main/e/eog/eog_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/f/file-roller/file-roller_43.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/f/five-or-more/five-or-more_3.32.3-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/f/fonts-cantarell/fonts-cantarell_0.303.1-1_all.deb
wget -c https://kali.download/kali/pool/main/f/four-in-a-row/four-in-a-row_3.38.1-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/f/fwupd/fwupd_1.9.9-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gcr/gcr_3.41.1-3_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gdebi/gdebi_0.9.5.7%2bnmu7_all.deb
wget -c https://kali.download/kali/pool/main/m/mutter/libmutter-13-0_45.0-3_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-settings-daemon/gnome-settings-daemon-common_45.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-disk-utility/gnome-disk-utility_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-settings-daemon/gnome-settings-daemon_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/glib2.0/libglib2.0-0_2.78.1-4_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-keyring/gnome-keyring-pkcs11_42.1-1%2bb2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-keyring/gnome-keyring_42.1-1%2bb2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-session/gnome-session_45.0-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-session/gnome-session-bin_45.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gdm3/gdm3_45.0.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/ghex/ghex_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gdm3/gir1.2-gdm-1.0_45.0.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-menus/gir1.2-gmenu-3.0_3.36.0-1.1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-autoar/gir1.2-gnomeautoar-0.1_0.4.4-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/gir1.2-gnomebg-4.0_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-bluetooth3/gir1.2-gnomebluetooth-3.0_42.6-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/gir1.2-gnomedesktop-3.0_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/gir1.2-gnomedesktop-4.0_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-online-accounts/gir1.2-goa-1.0_3.48.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgtop2/gir1.2-gtop-2.0_2.40.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/n/nautilus/gir1.2-nautilus-4.0_44.2.1-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libs/libsoup2.4/gir1.2-soup-2.4_2.74.3-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libs/libsoup3/gir1.2-soup-3.0_3.4.4-2_amd64.deb
wget -c https://kali.download/kali/pool/main/t/totem/gir1.2-totem-1.0_43.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gjs/gjs_1.78.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgnomekbd/gkbd-capplet_3.28.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/m/meta-gnome3/gnome_44%2b1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-2048/gnome-2048_3.38.2-3%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/i/iagno/iagno_3.38.1-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-themes-extra/gnome-accessibility-themes_3.28-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-applets/gnome-applets_3.50.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-applets/gnome-applets-data_3.50.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-backgrounds/gnome-backgrounds_45.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-bluetooth3/gnome-bluetooth-3-common_42.6-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-bluetooth3/gnome-bluetooth-sendto_42.6-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-brave-icon-theme_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-calculator/gnome-calculator_45.0.2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-calendar/gnome-calendar_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gjs/libgjs0g_1.78.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-characters/gnome-characters_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-chess/gnome-chess_43.2-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-clocks/gnome-clocks_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-color-manager/gnome-color-manager_3.36.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-colors_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-colors-common_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-contacts/gnome-contacts_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-control-center/gnome-control-center-data_45.1-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-control-center/gnome-control-center_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-remote-desktop/gnome-remote-desktop_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/m/meta-gnome3/gnome-core_44%2b1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/gnome-desktop3-data_44.0-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-dictionary/gnome-dictionary_40.0-3_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-dust-icon-theme_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-flashback/gnome-flashback_3.50.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-screensaver/gnome-screensaver_3.6.1-13%2bb2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-flashback/gnome-session-flashback_3.50.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-flashback/gnome-flashback-common_3.50.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-font-viewer/gnome-font-viewer_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/m/meta-gnome3/gnome-games_44%2b1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-human-icon-theme_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-icon-theme/gnome-icon-theme_3.12.0-5_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-illustrious-icon-theme_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-initial-setup/gnome-initial-setup_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-klotski/gnome-klotski_3.38.2-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-logs/gnome-logs_45%7ebeta-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-mahjongg/gnome-mahjongg_3.40.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-maps/gnome-maps_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-menus/gnome-menus_3.36.0-1.1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-mines/gnome-mines_40.1-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-multi-writer/gnome-multi-writer_3.32.1-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-music/gnome-music_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-nibbles/gnome-nibbles_4.0%7erc2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-noble-icon-theme_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-online-accounts/gnome-online-accounts_3.48.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-panel/gnome-panel_3.50.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-panel/gnome-panel-data_3.50.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-power-manager/gnome-power-manager_43.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-robots/gnome-robots_40.0-2%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-screenshot/gnome-screenshot_41.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/x/xdg-desktop-portal-gnome/xdg-desktop-portal-gnome_44.2-3_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell/gnome-shell-extension-prefs_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell/gnome-shell-common_45.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell/gnome-shell_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extensions/gnome-shell-extensions_45.1-1kali1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extension-appindicator/gnome-shell-extension-appindicator_57-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extension-dash-to-panel/gnome-shell-extension-dash-to-panel_59-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extension-dashtodock/gnome-shell-extension-dashtodock_89-0kali1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extension-desktop-icons-ng/gnome-shell-extension-desktop-icons-ng_46%2breally47.0.7-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extension-easyscreencast/gnome-shell-extension-easyscreencast_1.7.1-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extension-gsconnect/gnome-shell-extension-gsconnect_55-4_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-shell-extension-tiling-assistant/gnome-shell-extension-tiling-assistant_44-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-software/gnome-software-plugin-snap_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-software/gnome-software_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-software/gnome-software-common_45.1-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-software/gnome-software-plugin-flatpak_45.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-sound-recorder/gnome-sound-recorder_43%7ebeta-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-sudoku/gnome-sudoku_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-sushi/gnome-sushi_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-system-monitor/gnome-system-monitor_45.0.2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/s/system-tools-backends/system-tools-backends_2.10.2-3.1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-system-tools/gnome-system-tools_3.0.0-9.1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-taquin/gnome-taquin_3.38.1-2%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-terminal/gnome-terminal_3.50.0-1kali1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-terminal/gnome-terminal-data_3.50.0-1kali1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-tetravex/gnome-tetravex_3.38.2-3_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-text-editor/gnome-text-editor_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/k/kali-themes/gnome-theme-kali_2023.4.5_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-themes-extra/gnome-themes-extra_3.28-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-themes-extra/gnome-themes-extra-data_3.28-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-tweaks/gnome-tweaks_42%7ebeta-4_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-user-docs/gnome-user-docs_45.1-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-user-share/gnome-user-share_43.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-video-effects/gnome-video-effects_0.6.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-weather/gnome-weather_45.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-wine-icon-theme_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-colors/gnome-wise-icon-theme_5.5.1-2.1_all.deb
wget -c https://kali.download/kali/pool/main/g/gparted/gparted_1.5.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gparted/gparted-common_1.5.0-1_all.deb
wget -c https://kali.download/kali/pool/main/g/gtk2-engines/gtk2-engines_2.20.2-5%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/guake/guake_3.10-1_all.deb
wget -c https://kali.download/kali/pool/main/i/intltool-debian/intltool-debian_0.35.0%2b20060710.6_all.deb
wget -c https://kali.download/kali/pool/main/k/kali-meta/kali-desktop-gnome_2023.4.6_all.deb
wget -c https://kali.download/kali/pool/main/liba/libao/libao-common_1.2.2%2b20180113-1.1_all.deb
wget -c https://kali.download/kali/pool/main/liba/libao/libao4_1.2.2%2b20180113-1.1_amd64.deb
wget -c https://kali.download/kali/pool/main/b/brasero/libbrasero-media3-1_3.12.3-2_amd64.deb
wget -c https://kali.download/kali/pool/main/e/exo/libexo-2-0_4.18.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/e/exo/libexo-common_4.18.0-1_all.deb
wget -c https://kali.download/kali/pool/main/f/flatpak/libflatpak0_1.14.4-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libf/libfm/libfm4_1.3.2-4_amd64.deb
wget -c https://kali.download/kali/pool/main/f/fwupd/libfwupd2_1.9.9-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gtk%2b3.0/libgail-3-0_3.24.38-6_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gtk%2b2.0/libgail-common_2.24.33-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gtk%2b2.0/libgail18_2.24.33-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gdm3/libgdm1_45.0.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gexiv2/libgexiv2-2_0.14.2-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libglib-object-introspection-perl/libglib-object-introspection-perl_0.051-1_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libglib-perl/libglib-perl_1.329.3-3_amd64.deb
wget -c https://kali.download/kali/pool/main/g/glib2.0/libglib2.0-bin_2.78.1-4_amd64.deb
wget -c https://kali.download/kali/pool/main/g/glib2.0/libglib2.0-data_2.78.1-4_all.deb
wget -c https://kali.download/kali/pool/main/g/glib2.0/libglib2.0-dev_2.78.1-4_amd64.deb
wget -c https://kali.download/kali/pool/main/g/glib2.0/libglib2.0-dev-bin_2.78.1-4_amd64.deb
wget -c https://kali.download/kali/pool/main/g/glibmm2.4/libglibmm-2.4-1v5_2.66.6-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/glibmm2.68/libglibmm-2.68-1_2.78.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-autoar/libgnome-autoar-0-0_0.4.4-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-autoar/libgnome-autoar-gtk-0-0_0.4.4-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/libgnome-bg-4-2_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-bluetooth3/libgnome-bluetooth-3.0-13_42.6-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-bluetooth3/libgnome-bluetooth-ui-3.0-13_42.6-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/libgnome-desktop-3-20_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/libgnome-desktop-4-2_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgnome-games-support1/libgnome-games-support-1-3_1.8.2-5_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgnome-games-support/libgnome-games-support-2-4_2.0.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgnome-games-support1/libgnome-games-support-common_1.8.2-5_all.deb
wget -c https://kali.download/kali/pool/main/libg/libgnome-games-support/libgnome-games-support-common2_2.0.0-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-menus/libgnome-menu-3-0_3.36.0-1.1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-panel/libgnome-panel3_3.50.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-desktop/libgnome-rr-4-2_44.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgnomekbd/libgnomekbd-common_3.28.1-1_all.deb
wget -c https://kali.download/kali/pool/main/libg/libgnomekbd/libgnomekbd8_3.28.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-online-accounts/libgoa-1.0-0b_3.48.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-online-accounts/libgoa-1.0-common_3.48.0-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-online-accounts/libgoa-backend-1.0-1_3.48.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgsf/libgsf-1-114_1.14.51-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgsf/libgsf-1-common_1.14.51-2_all.deb
wget -c https://kali.download/kali/pool/main/libg/libgsf/libgsf-bin_1.14.51-2_amd64.deb
wget -c https://kali.download/kali/pool/main/g/ghex/libgtkhex-4-1_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgtop2/libgtop-2.0-11_2.40.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libg/libgtop2/libgtop2-common_2.40.0-2_all.deb
wget -c https://kali.download/kali/pool/main/m/mate-control-center/libmate-slab0_1.26.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/m/menu-cache/libmenu-cache3_1.1.0-1.1_amd64.deb
wget -c https://kali.download/kali/pool/main/m/mozjs115/libmozjs-115-0_115.5.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/n/nautilus/libnautilus-extension4_44.2.1-2_amd64.deb
wget -c https://kali.download/kali/pool/main/o/openbox/libobrender32v5_3.6.1-11_amd64.deb
wget -c https://kali.download/kali/pool/main/o/openbox/libobt2v5_3.6.1-11_amd64.deb
wget -c https://kali.download/kali/pool/main/g/gnome-keyring/libpam-gnome-keyring_42.1-1%2bb2_amd64.deb
wget -c https://kali.download/kali/pool/main/libp/libproxy/libproxy1-plugin-gsettings_0.4.18-1.2_amd64.deb
wget -c https://kali.download/kali/pool/main/libr/libreoffice/libreoffice_7.5.9%7erc1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/libr/libreoffice/libreoffice-gnome_7.5.9%7erc1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/libr/libreoffice/libreoffice-gtk3_7.5.9%7erc1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/libr/libreoffice/libreoffice-style-elementary_7.5.9%7erc1-1_all.deb
wget -c https://kali.download/kali/pool/main/r/rygel/librygel-core-2.8-0_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rygel/librygel-db-2.8-0_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rygel/librygel-renderer-2.8-0_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rygel/librygel-renderer-gst-2.8-0_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rygel/librygel-server-2.8-0_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/libs/libsoup3/libsoup-3.0-0_3.4.4-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libs/libsoup2.4/libsoup-gnome2.4-1_2.74.3-2_amd64.deb
wget -c https://kali.download/kali/pool/main/libs/libsoup2.4/libsoup2.4-1_2.74.3-2_amd64.deb
wget -c https://kali.download/kali/pool/main/s/startup-notification/libstartup-notification0_0.12-6%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/t/tumbler/libtumbler-1-0_4.18.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/libx/libxml%2b%2b2.6/libxml%2b%2b2.6-2v5_2.40.1-3_amd64.deb
wget -c https://kali.download/kali/pool/main/libx/libxml-libxml-perl/libxml-libxml-perl_2.0207%2bdfsg%2breally%2b2.0134-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/libx/libxml2/libxml2_2.9.14%2bdfsg-1.3_amd64.deb
wget -c https://kali.download/kali/pool/main/libx/libxml2/libxml2-dev_2.9.14%2bdfsg-1.3_amd64.deb
wget -c https://kali.download/kali/pool/main/libx/libxml2/libxml2-utils_2.9.14%2bdfsg-1.3_amd64.deb
wget -c https://kali.download/kali/pool/main/y/yelp/libyelp0_42.2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/l/lxappearance/lxappearance_0.6.3-5_amd64.deb
wget -c https://kali.download/kali/pool/main/b/brisk-menu/mate-applet-brisk-menu_0.6.2-2_amd64.deb
wget -c https://kali.download/kali/pool/main/m/mate-desktop-environment/mate-desktop-environment-core_1.26.0%2b1_all.deb
wget -c https://kali.download/kali/pool/main/m/mate-desktop-environment/mate-desktop-environment_1.26.0%2b1_all.deb
wget -c https://kali.download/kali/pool/main/m/mate-themes/mate-themes_3.22.24-1_all.deb
wget -c https://kali.download/kali/pool/main/m/mate-user-guide/mate-user-guide_1.26.2-1_all.deb
wget -c https://kali.download/kali/pool/main/n/nautilus/nautilus_44.2.1-2_amd64.deb
wget -c https://kali.download/kali/pool/main/n/nautilus/nautilus-data_44.2.1-2_all.deb
wget -c https://kali.download/kali/pool/main/g/gnome-terminal/nautilus-extension-gnome-terminal_3.50.0-1kali1_amd64.deb
wget -c https://kali.download/kali/pool/main/n/network-manager-fortisslvpn/network-manager-fortisslvpn-gnome_1.4.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/n/network-manager-applet/network-manager-gnome_1.34.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/n/network-manager-l2tp/network-manager-l2tp-gnome_1.20.10-1_amd64.deb
wget -c https://kali.download/kali/pool/main/n/network-manager-openconnect/network-manager-openconnect-gnome_1.2.10-1_amd64.deb
wget -c https://kali.download/kali/pool/main/n/network-manager-openvpn/network-manager-openvpn-gnome_1.10.2-4_amd64.deb
wget -c https://kali.download/kali/pool/main/n/network-manager-pptp/network-manager-pptp-gnome_1.2.12-3_amd64.deb
wget -c https://kali.download/kali/pool/main/n/network-manager-vpnc/network-manager-vpnc-gnome_1.2.8-7_amd64.deb
wget -c https://kali.download/kali/pool/main/o/openbox/openbox_3.6.1-11_amd64.deb
wget -c https://kali.download/kali/pool/main/o/orca/orca_45.1-2_all.deb
wget -c https://kali.download/kali/pool/main/p/pinentry/pinentry-gnome3_1.2.1-3_amd64.deb
wget -c https://kali.download/kali/pool/main/p/policykit-1-gnome/policykit-1-gnome_0.105-8_amd64.deb
wget -c https://kali.download/kali/pool/main/p/policykit-1/polkitd_123-3%2bkali1_amd64.deb
wget -c https://repo.protonvpn.com/debian/dists/stable/main/binary-all/proton-vpn-gnome-desktop_0.2.0-1_all.deb
wget -c https://kali.download/kali/pool/main/p/pygobject/python3-gi_3.46.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/p/pygobject/python3-gi-cairo_3.46.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/p/python-keyring/python3-keyring_24.3.0-1_all.deb
wget -c https://kali.download/kali/pool/main/libx/libxml2/python3-libxml2_2.9.14%2bdfsg-1.3_amd64.deb
wget -c https://kali.download/kali/pool/main/p/python-secretstorage/python3-secretstorage_3.3.3-2_all.deb
wget -c https://kali.download/kali/pool/main/r/remmina/remmina-plugin-secret_1.4.31%2bdfsg-2_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rhythmbox/rhythmbox_3.4.7-1_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rygel/rygel_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rygel/rygel-playbin_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/r/rygel/rygel-tracker_0.42.4-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/s/seahorse/seahorse_43.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/s/shared-mime-info/shared-mime-info_2.2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/s/shotwell/shotwell-common_0.32.3-1_all.deb
wget -c https://kali.download/kali/pool/main/s/shotwell/shotwell_0.32.3-1_amd64.deb
wget -c https://kali.download/kali/pool/main/s/switcheroo-control/switcheroo-control_2.6-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/t/tali/tali_40.9-1%2bb1_amd64.deb
wget -c https://kali.download/kali/pool/main/t/tecla/tecla_45.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/t/totem/totem_43.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/t/totem/totem-common_43.0-2_all.deb
wget -c https://kali.download/kali/pool/main/t/totem/totem-plugins_43.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/t/tumbler/tumbler_4.18.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/d/docker/wmdocker_1.5-4_amd64.deb
wget -c https://kali.download/kali/pool/main/x/xdg-desktop-portal-gtk/xdg-desktop-portal-gtk_1.15.1-1_amd64.deb
wget -c https://kali.download/kali/pool/main/x/xfce4-places-plugin/xfce4-places-plugin_1.8.3-1_amd64.deb
wget -c https://kali.download/kali/pool/main/x/xfwm4/xfwm4_4.18.0-1_amd64.deb
wget -c https://kali.download/kali/pool/main/x/xiccd/xiccd_0.3.0-2_amd64.deb
wget -c https://kali.download/kali/pool/main/x/xsettingsd/xsettingsd_1.0.2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/y/yelp/yelp_42.2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/z/zenity/zenity_3.44.2-1_amd64.deb
wget -c https://kali.download/kali/pool/main/z/zenity/zenity-common_3.44.2-1_all.deb
dpkg -i *.deb
apt --fix-broken install -y
dpkg -i *.deb
apt install aptitude -y && aptitude install locales -y && locale-gen en_US.UTF-8 && localedef -i en_US -f UTF-8 en_US.UTF-8 && export LANGUAGE=en_US.UTF-8 && export LANG=en_US.UTF-8 && export LC_ALL=en_US.UTF-8 && locale-gen en_US.UTF-8 && apt-get update -y && apt-get full-upgrade -y && aptitude install wget -y && apt-get install python3 python3-venv python3-pip -y && apt-get autoclean && apt-get clean cache && apt update -y && apt-get full-upgrade -y
reboot
